site_name: 现代CMake教程
plugins:
  - snippet
  - search
  - macros
  - print-site

extra_javascript:
  - extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css: 
  - extra.css
nav:
  - 章节列表: 
    - index.md
    - 环境搭建.md
  - 关于: about.md
