site_name: 现代CMake教程
site_dir: site
plugins:
  - snippet
  - search
  - macros
  - print-site
extra_javascript:
  - extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css: 
  - extra.css
nav:
  - 章节列表: 
    - index.md
    - 环境搭建.md
    - 现代CMake的核心概念.md
    - 最小构建.md
    - find_package案例.md
    - CMakePresets.md
    - 设置目标属性.md
    - QtCMake.md
    - 基本常识.md
    - 参考链接.md
  - 经典案例:
    - 普通CMake项目.md
    - QtCMake项目.md
    - CMake制作库.md
  - 基本常识: 基本常识.md 
  - 关于: about.md
